INSERT INTO Locations (locationID, name, description, latitude, longitude, difficulty_level, hints, puzzle_text, next_location_id, is_active, createdAt, updatedAt)
VALUES  (4, 'Mont des Arts / Kunstberg', 'Cultural hill with city views', 50.8440, 4.3560, 2, 'Big stairs between museums', NULL, NULL, TRUE, NOW(), NOW()),
  (5, 'Triomfboog van het Jubelpark', 'Triumphal arch in Cinquantenaire Park', 50.8407, 4.3900, 2, 'Archway in big park with museums', NULL, NULL, TRUE, NOW(), NOW()),
  (6, 'Parc du Cinquantenaire', 'Large park with museums and arch', 50.8390, 4.3870, 2, 'Park with aviation and auto museums', NULL, NULL, TRUE, NOW(), NOW()),
  (7, 'Koninklijke Musea voor Schone Kunsten', 'Royal Museums of Fine Arts', 50.8425, 4.3610, 2, 'Art museums near Mont des Arts', NULL, NULL, TRUE, NOW(), NOW()),
  (8, 'Koninklijk Paleis van Brussel', 'Royal Palace of Brussels', 50.8390, 4.3660, 2, 'Big palace facing park', NULL, NULL, TRUE, NOW(), NOW()),
  (9, 'Warandepark', 'Park in front of Royal Palace', 50.8395, 4.3640, 1, 'Park between palace and parliament', NULL, NULL, TRUE, NOW(), NOW()),
  (10, 'Belgisch Parlement', 'Belgian Federal Parliament', 50.8430, 4.3620, 2, 'Parliament building near Royal Palace', NULL, NULL, TRUE, NOW(), NOW()),
  (11, 'Black Tower (Zwarte Toren)', 'Fairy-tale like dark turret overgrown with ivy', 50.7985, 4.3130, 4, 'Dark turret at cemetery entrance', NULL, NULL, TRUE, NOW(), NOW()),
  (12, 'Kunstberg-trappen', 'Famous stairs with city panorama', 50.8440, 4.3560, 2, 'Big staircase with city view', NULL, NULL, TRUE, NOW(), NOW()),
  (13, 'Dudenpark', 'Large park with panoramic views', 50.8110, 4.3120, 3, 'Park near Forest with city views', NULL, NULL, TRUE, NOW(), NOW()),
  (14, 'Basiliek van Koekelberg', 'Massive basilica, 5th largest church', 50.8540, 4.2860, 3, 'Huge church visible from city', NULL, NULL, TRUE, NOW(), NOW()),
  (15, 'Park Thurn & Taxis Bridge View', 'Panoramic view from bridge', 50.8620, 4.3450, 3, 'Bridge over canal near Thurn & Taxis', NULL, NULL, TRUE, NOW(), NOW()),
  (16, 'Kruidtuin (Le Botanique)', 'Botanical garden and concert hall', 50.8550, 4.3620, 2, 'Greenhouses near Rogier metro', NULL, NULL, TRUE, NOW(), NOW()),
  (17, 'Bois de la Cambre', 'Large park with lake and island', 50.8150, 4.3620, 2, 'Big park south of city center', NULL, NULL, TRUE, NOW(), NOW()),
  (18, 'Chalet Robinson', 'Island restaurant in Bois de la Cambre', 50.8155, 4.3650, 4, 'Restaurant reached by boat', NULL, NULL, TRUE, NOW(), NOW()),
  (19, 'Jardin du Maelbeek', 'Small garden near EU quarter', 50.8400, 4.3800, 3, 'Garden near Schuman metro', NULL, NULL, TRUE, NOW(), NOW()),
  (20, 'Place du Jeu de Balle', 'Flea market square', 50.8360, 4.3480, 2, 'Morning flea market square', NULL, NULL, TRUE, NOW(), NOW()),
  (21, 'Rue des Bouchers', 'Touristy restaurant street', 50.8470, 4.3530, 1, 'Street full of restaurants near Grand Place', NULL, NULL, TRUE, NOW(), NOW()),
  (22, 'Rue du Marché aux Fromages', 'Historic street near Grand Place', 50.8465, 4.3540, 2, 'Street parallel to butcher street', NULL, NULL, TRUE, NOW(), NOW()),
  (23, 'Villa Empain', 'Art Deco villa with modern art', 50.8230, 4.4130, 4, 'White villa in Ixelles', NULL, NULL, TRUE, NOW(), NOW()),
  (24, 'Koninklijke Serres van Laeken', 'Royal greenhouses (seasonal)', 50.8800, 4.3400, 4, 'Greenhouses near royal palace', NULL, NULL, TRUE, NOW(), NOW()),
  (25, 'Japanese Tower', 'Pagoda in Laeken Park', 50.8800, 4.3420, 3, 'Pagoda next to Chinese pavilion', NULL, NULL, TRUE, NOW(), NOW()),
  (26, 'Monument to the Dynasty', 'Column monument in park', 50.8390, 4.3870, 3, 'Tall column in Cinquantenaire', NULL, NULL, TRUE, NOW(), NOW()),
  (27, 'Hallepoort', 'Medieval city gate', 50.8340, 4.3480, 2, 'Gatehouse near south station', NULL, NULL, TRUE, NOW(), NOW()),
  (28, 'Poelaertplein', 'Square with Justice Palace view', 50.8310, 4.3500, 2, 'Square above Marolles', NULL, NULL, TRUE, NOW(), NOW()),
  (29, 'Wiels Rooftop', 'Contemporary art center rooftop', 50.8130, 4.3350, 4, 'Art center in former brewery', NULL, NULL, TRUE, NOW(), NOW()),
  (30, 'Het Goudblommeke in Papier', 'Historic surrealist café', 50.8490, 4.3580, 3, 'Old café near Bourse', NULL, NULL, TRUE, NOW(), NOW()),
  (31, 'À la Mort Subite', 'Classic Belgian café', 50.8490, 4.3550, 2, 'Café near Grand Place', NULL, NULL, TRUE, NOW(), NOW()),
  (32, 'Le Cirio', 'Historic café since 1880', 50.8505, 4.3485, 2, 'Old café on Bourse street', NULL, NULL, TRUE, NOW(), NOW()),
  (33, 'Au Derby', 'Traditional Brussels café', 50.8520, 4.3470, 3, 'Café near Place Fontainas', NULL, NULL, TRUE, NOW(), NOW()),
  (34, '’t Spinnekopke', 'Oldest canal-side café', 50.8550, 4.3450, 3, 'Café by Brussels canal', NULL, NULL, TRUE, NOW(), NOW()),
  (35, 'Les Brigittines', 'Arts center in old convent', 50.8330, 4.3430, 4, 'Convent near Midi station', NULL, NULL, TRUE, NOW(), NOW()),
  (36, 'Bouillon Bruxelles', 'Traditional soup restaurant', 50.8470, 4.3600, 2, 'Cheap traditional eatery', NULL, NULL, TRUE, NOW(), NOW()),
  (37, 'Belga Queen', 'Restaurant in old bank building', 50.8470, 4.3600, 3, 'Restaurant in bank vault', NULL, NULL, TRUE, NOW(), NOW()),
  (38, 'Vossenstraat Steegjes', 'Street art alleyways', 50.7980, 4.3310, 3, 'Alleys with murals in Ixelles', NULL, NULL, TRUE, NOW(), NOW()),
  (39, 'Horta Gallery', 'Art Nouveau architecture', 50.8230, 4.3660, 3, 'Gallery with Horta designs', NULL, NULL, TRUE, NOW(), NOW()),
  (40, 'Place du Petit Sablon', 'Small square with statues', 50.8410, 4.3590, 2, 'Small square near Grand Sablon', NULL, NULL, TRUE, NOW(), NOW()),
  (41, 'Place du Grand Sablon', 'Antique market square', 50.8415, 4.3600, 2, 'Square with chocolate shops', NULL, NULL, TRUE, NOW(), NOW()),
  (42, 'MIM Terras', 'Musical Instruments Museum terrace', 50.8490, 4.3600, 3, 'Museum terrace with views', NULL, NULL, TRUE, NOW(), NOW()),
  (43, 'Jubelpark Arcade Rooftop View', 'Rooftop view from arcade', 50.8400, 4.3900, 4, 'Rooftop in Cinquantenaire arcade', NULL, NULL, TRUE, NOW(), NOW()),
  (44, 'Metrostation Pannenhuis', 'Historic metro station', 50.8600, 4.3400, 3, 'Metro station near North station', NULL, NULL, TRUE, NOW(), NOW()),
  (45, 'Begraafplaats van Elsene', 'Ixelles Cemetery', 50.8220, 4.3780, 3, 'Cemetery with famous graves', NULL, NULL, TRUE, NOW(), NOW()),
  (46, 'Serres van Botanique', 'Botanical garden greenhouses', 50.8550, 4.3620, 3, 'Greenhouses behind Botanique', NULL, NULL, TRUE, NOW(), NOW()),
  (47, 'Park van Vorst', 'Forest Park', 50.8110, 4.2900, 2, 'Large park in Forest', NULL, NULL, TRUE, NOW(), NOW()),
  (48, 'Lambermont-boulevard', 'Scenic boulevard with views', 50.8500, 4.4100, 3, 'Boulevard near Tervuren', NULL, NULL, TRUE, NOW(), NOW()),
  (49, 'Jupiter Panorama', 'Panoramic viewpoint', 50.8300, 4.4200, 4, 'Viewpoint named after Jupiter', NULL, NULL, TRUE, NOW(), NOW()),
  (50, 'Scheutbospark', 'Wooded park in Anderlecht', 50.8400, 4.2700, 3, 'Park in Scheut neighborhood', NULL, NULL, TRUE, NOW(), NOW()),
  (51, 'Puppet Theatre Toone', 'Historic puppet theater since 1830, down alley from Grand Place. Pub with marionettes.', 50.8476, 4.3523, 3, 'Impasse Ste-Pétronille, 66 Rue du Marché aux Herbes', NULL, NULL, TRUE, NOW(), NOW()),
  (52, 'Le Cercueil', 'Macabre-themed bar offering hell-bent bar-hopping experience.', 50.8476, 4.3523, 4, '10 Haringstraat (same building as Toone)', NULL, NULL, TRUE, NOW(), NOW()),
  (53, 'Cemetery Dieweg', 'Abandoned cemetery from 1866 cholera epidemic, overcrowded and closed 1958.', 50.7980, 4.3130, 5, '95 Dieweg, Uccle', NULL, NULL, TRUE, NOW(), NOW()),
  (54, 'Musée des Arbalétriers', 'Hidden crossbowmen museum with remarkable hospitality.', 50.7980, 4.3130, 5, '95 Dieweg, Uccle (at cemetery entrance)', NULL, NULL, TRUE, NOW(), NOW()),
  (55, 'Jardin du Fleuriste', 'Secret garden at Fleuriste de Stuyvenberg.', 50.8800, 4.3500, 4, 'Fleuriste de Stuyvenberg, 1020 Bruxelles', NULL, NULL, TRUE, NOW(), NOW()),
  (56, 'Cemetery of Brussels (Evere)', 'Historic cemetery with Belgian national anthem composer and mayors.', 50.8800, 4.4100, 4, '1140 Evere', NULL, NULL, TRUE, NOW(), NOW()),
  (57, 'Kauwberg Nature Reserve', 'Wild meadows and city views adjacent to Parc de La Sauvagère.', 50.8700, 4.4200, 4, 'Near Tervuren', NULL, NULL, TRUE, NOW(), NOW()),
  (58, 'Bois de la Cambre Secret Island', 'Silent car-free island reached by small ferry in park lake.', 50.8155, 4.3650, 4, 'Take ferry from Chalet Robinson', NULL, NULL, TRUE, NOW(), NOW()),
  (59, 'Fin-de-Siècle Museum', '1884-1914 art explosion (Art Nouveau, Symbolism), quieter than Magritte.', 50.8415, 4.3590, 3, 'Rue de la Régence 3, near Grand Sablon', NULL, NULL, TRUE, NOW(), NOW()),
  (60, 'Sewer Museum (Musée des Égouts)', 'Working sewer tour about Brussels water management.', 50.8310, 4.3300, 4, 'Porte d\'Anderlecht', NULL, NULL, TRUE, NOW(), NOW()),
  (61, 'Cantillon Brewery', 'Living museum of traditional lambic brewing since 1900.', 50.8210, 4.3310, 3, 'Rue Gheude 56, 1070 Anderlecht', NULL, NULL, TRUE, NOW(), NOW()),
  (62, 'Le Phare du Kanaal', 'Solitary lighthouse in industrial canal district.', 50.8700, 4.3400, 4, 'Quai des Charbonnages 40, 1080 Molenbeek', NULL, NULL, TRUE, NOW(), NOW()),
  (63, 'Zinneke Pis (Pissing Dog)', 'Bronze dog peeing on post, third peeing statue.', 50.8500, 4.3480, 3, 'Rue des Chartreux 35', NULL, NULL, TRUE, NOW(), NOW()),
  (64, 'Windmill of Lindekemale', 'Restored 18th-century windmill in Woluwe Park.', 50.8400, 4.4300, 4, 'Av. Jean-François Debecker 2, 1200 Woluwe-Saint-Lambert', NULL, NULL, TRUE, NOW(), NOW()),
  (65, 'Abandoned Tower of Laeken', 'Ruined tower of former Church of Our Lady amidst cemetery.', 50.8700, 4.3300, 5, 'Laeken cemetery area', NULL, NULL, TRUE, NOW(), NOW()),
  (66, 'Cité Hellemans', 'Early 20th-century art deco social housing citadel.', 50.8340, 4.3450, 4, 'Rue des Tonneliers 5, behind Marolles', NULL, NULL, TRUE, NOW(), NOW()),
  (67, 'Van Buuren Museum Courtyard', '"Garden of the Heart" landscape design, quieter than city parks.', 50.8020, 4.3600, 4, 'Av. Léo Errera 41, 1180 Uccle', NULL, NULL, TRUE, NOW(), NOW()),
  (68, 'Église Sainte-Marie Madeleine', 'Last remaining part of medieval abbey, feels ancient.', 50.8450, 4.3400, 4, 'Rue de la Chapelle 40', NULL, NULL, TRUE, NOW(), NOW()),
  (69, 'La Maison van Dyck', '1927 eclectic house with seashell/pebble facade.', 50.8600, 4.3800, 5, 'Rue de la Luzerne 55, 1030 Schaerbeek', NULL, NULL, TRUE, NOW(), NOW()),
  (70, 'La Maison de La Bellone', '17th-century mansion with Baroque facade and arts courtyard.', 50.8530, 4.3420, 4, 'Rue de Flandre 46', NULL, NULL, TRUE, NOW(), NOW()),
  (71, 'La Fontaine des Aveugles', 'Melancholic fountain of blind man and dog in small square.', 50.8450, 4.3500, 4, 'Place des Aveugles', NULL, NULL, TRUE, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  name=VALUES(name),
  description=VALUES(description),
  latitude=VALUES(latitude),
  longitude=VALUES(longitude),
  difficulty_level=VALUES(difficulty_level),
  hints=VALUES(hints),
  puzzle_text=VALUES(puzzle_text),
  next_location_id=VALUES(next_location_id),
  is_active=VALUES(is_active),
  updatedAt=VALUES(updatedAt);